package com.mefabc24.strata.tools.atlas

import com.badlogic.gdx.graphics.Texture
import com.badlogic.gdx.tools.texturepacker.TexturePacker
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.extension
import kotlin.io.path.isDirectory
import kotlin.io.path.isRegularFile
import kotlin.io.path.name

/** Paths and output name for one Strata-compatible texture atlas. */
data class AtlasPackingConfig(
    val sourceDirectory: Path,
    val outputDirectory: Path,
    val atlasName: String
)

/** Files generated by one atlas packing run. */
data class AtlasPackingResult(
    val metadata: Path,
    val pages: List<Path>
)

/** Packs PNG source trees with settings accepted by Strata world visuals. */
object TextureAtlasPacker {
    @JvmStatic
    fun pack(config: AtlasPackingConfig): AtlasPackingResult {
        validate(config)
        Files.createDirectories(config.outputDirectory)
        require(config.outputDirectory.isDirectory()) {
            "Atlas output path must be a directory: ${config.outputDirectory}"
        }

        clean(config.outputDirectory, config.atlasName)
        TexturePacker.process(
            settings(),
            config.sourceDirectory.toString(),
            config.outputDirectory.toString(),
            config.atlasName
        )

        val metadata = config.outputDirectory.resolve("${config.atlasName}.atlas")
        check(metadata.isRegularFile()) {
            "TexturePacker did not create atlas metadata: $metadata"
        }
        val pages = generatedPages(config.outputDirectory, config.atlasName)
        check(pages.isNotEmpty()) {
            "TexturePacker did not create any atlas pages for '${config.atlasName}'."
        }
        return AtlasPackingResult(metadata, pages)
    }

    /** Removes only metadata and PNG pages generated for [atlasName]. */
    @JvmStatic
    fun clean(outputDirectory: Path, atlasName: String): List<Path> {
        validateAtlasName(atlasName)
        if (!Files.exists(outputDirectory)) return emptyList()
        require(outputDirectory.isDirectory()) {
            "Atlas output path must be a directory: $outputDirectory"
        }

        val generated = buildList {
            val metadata = outputDirectory.resolve("$atlasName.atlas")
            if (metadata.isRegularFile()) add(metadata)
            addAll(generatedPages(outputDirectory, atlasName))
        }
        generated.forEach(Files::delete)
        return generated
    }

    private fun validate(config: AtlasPackingConfig) {
        validateAtlasName(config.atlasName)
        require(Files.exists(config.sourceDirectory)) {
            "Atlas source directory does not exist: ${config.sourceDirectory}"
        }
        require(config.sourceDirectory.isDirectory()) {
            "Atlas source path must be a directory: ${config.sourceDirectory}"
        }

        val containsPng = Files.walk(config.sourceDirectory).use { paths ->
            paths.anyMatch {
                it.isRegularFile() && it.extension.equals("png", ignoreCase = true)
            }
        }
        require(containsPng) {
            "Atlas source directory contains no PNG files: ${config.sourceDirectory}"
        }
    }

    private fun validateAtlasName(atlasName: String) {
        require(atlasName.isNotBlank()) {
            "Atlas name must not be blank."
        }
        require(atlasName == Path.of(atlasName).fileName.toString()) {
            "Atlas name must be a file name without directory components."
        }
    }

    private fun generatedPages(
        outputDirectory: Path,
        atlasName: String
    ): List<Path> {
        if (!outputDirectory.isDirectory()) return emptyList()
        val pagePattern = Regex("^${Regex.escape(atlasName)}(?:\\d+)?\\.png$")
        return Files.list(outputDirectory).use { paths ->
            paths.filter {
                it.isRegularFile() && pagePattern.matches(it.name)
            }.sorted().toList()
        }
    }

    private fun settings() = TexturePacker.Settings().apply {
        rotation = false
        stripWhitespaceX = false
        stripWhitespaceY = false
        filterMin = Texture.TextureFilter.Nearest
        filterMag = Texture.TextureFilter.Nearest

        paddingX = 2
        paddingY = 2
        edgePadding = true
        duplicatePadding = false
        bleed = false
        pot = true
        maxWidth = 2048
        maxHeight = 2048
        useIndexes = true
    }
}
